version: "3.9"

services:
  db:
    image: postgres:14
    restart: always
    container_name: pgdb_fastapi
    network_mode: host
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: appdb
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata

  adminer:
    image: adminer
    restart: always
    network_mode: host

volumes:
  app-db-data:
